### ISSUE TITLE
How should K8s applications interact with Bpf Maps managed via BPFD?

### ISSUE THREAD

**Issue by astoycos** [bpfd-dev/bpfd#255]
Shoutout @dave-tucker :) 

eBPF applications are composed of:

- Userspace
- Kernelspace
And the transport between these is eBPF maps.

Maps are inherently tied to their userspace and kernel components - they aren’t designed to be generic (although with BTF we can best effort decode the contents).
What bpfd is doing is taking loading away from userspace which means that userspace is left with the question - where’s my maps.
So from a K8s userspace deployment standpoint the following things are constant:

- The map name I need - which is baked into my program code

And the following things are variable:
 
- My bpf program UUID on the node I’m scheduled - I can use that find the map pin path
- The bpffs volume which is a The volume where the pin is

What I’d like is to find the most K8s native thing to handle the variable portions…
So ideally my deployment can be as generic as possible - with no node-specific config/variables required.
A couple of ideas:
For the UUID, I wonder whether we could use a downwardAPI mount.
User would annotate their pod with ebpf/config-name (where the config name is an EbpfProgramConfig)…
Then our controller would annotate ebpf/$name/id when the program is loaded….
The userspace program could find the program UUID without being overly coupled to k8s.
For the volume mount, it would be nice to somehow automate that, but that’s probably a longer term exercise…

**Comment by kot-begemot-uk** [comment]
Adding from the discussion on afxdp CNI.

We have figured out how to map bpfs into the container and allow non-privileged access to maps. The discussion was centered around XSK_MAP, but it applies to all other maps too.

That opens the question on how do we interact with bpfd and how do we map the right maps to the right container? 

The obvious solution here seems to have all maps which "belong" to a particular bpf program grouped in a single directory on bpfs and the directory named to match the program. F.E. named by UUID.

Coming back to this issue - if we aim to resolve this by having a UUID dir and all maps inside we will have a result usabel for the AFXDP CNI

**Comment by kot-begemot-uk** [comment]
AFXDP CNI issue: https://github.com/redhat-et/afxdp-network-operator/issues/6

**Comment by dave-tucker** [comment]
> The obvious solution here seems to have all maps which "belong" to a particular bpf program grouped in a single directory on bpfs and the directory named to match the program. F.E. named by UUID.

This is indeed the state of bpffs today!
There are still some things that need to be figured out to make the mount of that bpffs location inside of containers that need to access it seamless, but we're working on a design for that.
