### ISSUE TITLE
Allow ProceedOn to be updated via bpfd-agent

### ISSUE THREAD

**Issue by Billy99** [bpfd-dev/bpfd#313]
ProceedOn is an optional field for XDP and TC bpf programs. If not entered, bpfd set ProceedOn to default values. XDP and TC each have a different set of values and different default values, but in BpfProgramConfig CRD, there is one attribute that covers both XDP and TC. Because of this, ProceedOn in TC is not fully supported and once the BpfProgramConfig object is created, any changes to ProceedOn are ignored.

ProceedOn needs to be supported by TC and the user should be able to updated ProceedOn in the BpfProgramConfig and it be applied to bpfd properly.

**Comment by astoycos** [comment]
Done in #342
