### ISSUE TITLE
Reflect all bpf program state from nodes into k8s

### ISSUE THREAD

**Issue by dave-tucker** [bpfd-dev/bpfd#320]
bpfd should iterate all bpf programs on the host and load those into the k8s api.
to do this we will need to:

1. Support displaying information for all program types, even if we don't support loading them
2. Maintain a mapping between bpf fd and uuid on each node

**Comment by astoycos** [comment]
Maintain a mapping b/w Kernel ID (Int BpfProgram Counter for a specific Node) Can we turn this into a namespaced UUID (UUID5 RFC namespace for each node) to correlate it to a specific node?

**Comment by astoycos** [comment]
Blocked on API refactor #340

**Comment by astoycos** [comment]
Done in #570 and #605
