### ISSUE TITLE
Re-think multiple programs in a single `bpfProgram` Object

### ISSUE THREAD

**Issue by astoycos** [bpfd-dev/bpfd#324]
Currently in Bpfd-K8s `bpfProgramConfig` API we've built it to one day (for "network multi attach" programs) to be able to attach to multiple interfaces with a single object. 

we should be able to easily select: 

- An interface by name <Already Done>
- The default interface on the node
- All the interfaces on the node + Exceptions (i.e select everything on the node except `lo`) 
- All the pod interfaces (host side veths) 
- Specific pod interfaces (via a pod selector)

Therefore in the `bpfProgram` API the `programs` field is a map of `UUID:Metadata` 

```
// BpfProgramSpec defines the desired state of BpfProgram
type BpfProgramSpec struct {
	// ProgramMap is is a map with Keys: UUIDs, Values: BpfProgramMeta
	Programs map[string]BpfProgramMeta `json:"programs"`
}

// BpfProgramMeta defines the relevant metadata needed for a single
// running BpfProgram.
type BpfProgramMeta struct {
	// AttachPoint specifies what this BpfProgram is attached to
	// for some programs is may be nil.
	AttachPoint *BpfProgramAttachPoint `json:"attachpoint,omitempty"`

	// Maps is a map with Keys: Map Names, and Values: Map Pin paths
	Maps map[string]string `json:"maps"`
}
```

This isn't efficient, and could make things really difficult for users in the future.  I _think_ bpfd should simply make sure that if the same program is attached to multiple things that they all use the same UUID, maps, and pin points.  Then we could simply change the API to be something like 

```
// BpfProgramSpec defines the desired state of BpfProgram
type BpfProgramSpec struct {
	// ProgramMap is is a map with Keys: UUIDs, Values: BpfProgramMeta
	uuid string `json:"uuid"`

	// AttachPoint specifies what this BpfProgram is attached to
	// for some programs is may be nil.
	AttachPoint *BpfProgramAttachPoint `json:"attachpoint,omitempty"`

	// Maps is a map with Keys: Map Names, and Values: Map Pin paths
	Maps map[string]string `json:"maps"`        
}

```

**Comment by astoycos** [comment]
cc @Billy99

**Comment by Billy99** [comment]
> " I think bpfd should simply make sure that if the same program is attached to multiple things that they all use the same UUID, maps, and pin points."

Regarding Andrew's point above, I don't think this is what we want. For example, if XDP-Counter is my bpf program, and I want it loaded on all the pods on a nodes, I don't want them sharing a single map. I want the counts for each individual pod.

**Comment by Billy99** [comment]
I was actually brainstorming in this topic this afternoon. So early thoughts:

The `attachpoint` structure (used by both BpfProgramConfig and BpfProgram) looks like:

```
// BpfProgramAttachPoint defines the allowed attach points
// for a program loaded via bpfd Exactly one attach point must
// be set.
// +kubebuilder:validation:MaxProperties=1
// +kubebuilder:validation:MinProperties=1
type BpfProgramAttachPoint struct {
	NetworkMultiAttach *BpfNetworkMultiAttach `json:"networkmultiattach,omitempty"`
	SingleAttach *BpfSingleAttach `json:"singleattach,omitempty"`
}

type BpfNetworkMultiAttach struct {
	Interface string `json:"interface"`
	Priority int32 `json:"priority"`
	Direction string `json:"direction"`
	ProceedOn []ProceedOnValue `json:"proceedon"`
}
```

The `interface` in the `BpfNetworkMultiAttach` becomes a `selector`:

```
type BpfNetworkMultiAttach struct {
	Selector string `json:"selector"`
	Side string 'json""side"`           # (Host or Pod side of veth=pair)
	Priority int32 `json:"priority"`
	Direction string `json:"direction"`
	ProceedOn []ProceedOnValue `json:"proceedon"`
}

// Selector defines interface to attach too/
// +kubebuilder:validation:MaxProperties=1
// +kubebuilder:validation:MinProperties=1
type Selector struct {
	Interface *string `json:"interface"`
	PodLabel *string `json:"podLabel"`
	IPAddress *string `json:"ipaddress"`  # Don't like, just brainstorming
        Primary *boolean `json:"primaryInterface"`
}
```

**Comment by Billy99** [comment]
### BpfProgram CRD Object Updates

The BpfProgram will probably need to be reworked to support attaching a given BPF Program to a set of interfaces (like a Pod Label).

Example of the BpfProgram currently:
```
apiVersion: bpfd.io/v1alpha1
kind: BpfProgram
metadata:
:
spec:
  programs:
    80a140a1-7371-4e66-8f2c-725b4b9bec3d:
      attachpoint:
        networkmultiattach:
          direction: NONE
          interface: eth0
          priority: 55
          proceedon: []
      maps:
        xdp_stats_map: /run/bpfd/fs/maps/80a140a1-7371-4e66-8f2c-725b4b9bec3d/xdp_stats_map
status:
  conditions:
  - lastTransitionTime: "2023-01-27T14:35:02Z"
    message: Successfully loaded bpfProgram
    reason: bpfdLoaded
    status: "True"
    type: Loaded
```

The Spec contains a map of programs (program is an instance of the BPF Program running on the node) indexed by the UUID, whereeach program has an AttachPoint  and a Map of pinned maps. The AttachPoint is the config from the BpfProgramConfig object, and is the same for every program, so it should be pulled up a level, out of the list of programs, and replaced by the interface the program is loaded on.

The BpfProgram will be tracking multiple instances of the BPF Program, so there needs to be a way to get status of each program. Either:
- The `status.conditions` needs to be a map indexed by UUID (like programs). This may not be possible because `conditions` is a bultin type, or may be too messy because of the nature of how conditions work.  OTHERWISE:
- The `status.conditions` tracks whether all programs successfully loaded or not, and a `status` and `reason` are added to the programs map

Example of the proposed BpfProgram:
```
apiVersion: bpfd.io/v1alpha1
kind: BpfProgram
metadata:
:
spec:
+  node: bpfd-deployment-worker
+  type: XDP
+  attachpoint:
+    networkmultiattach:
+      direction: NONE
+      selector:
+        interface: eth0
+        -- OR --
+        podLabel: nginx
+           host or pod side
+        -- OR --
+        ipaddress: 10.244.0.3  <- Don't like, just brainstorming
+        -- OR --
+        primaryInterface: true
  programs:
    80a140a1-7371-4e66-8f2c-725b4b9bec3d:
-      attachpoint:
-        networkmultiattach:
-          direction: NONE
-          interface: eth0
-          priority: 55
-          proceedon: []
+      interface: veth4536
+      status: "True"
+      reason: bpfdLoaded
      maps:
        xdp_stats_map: /run/bpfd/fs/maps/80a140a1-7371-4e66-8f2c-725b4b9bec3d/xdp_stats_map
status:
  conditions:
  - lastTransitionTime: "2023-01-27T14:35:02Z"
    message: Successfully loaded bpfProgram
    reason: bpfdLoaded
    status: "True"
    type: Loaded
```

**Comment by astoycos** [comment]
I think this is mostly completed in #342 Happy to hear any more thoughts here though @Billy99

**Comment by astoycos** [comment]
Follow up in #459
