### ISSUE TITLE
Support Uprobes

### ISSUE THREAD

**Issue by dave-tucker** [bpfd-dev/bpfd#369]
Note: This should probably happen after #342

As a user of bpfd, I would like the ability to load uprobes to trace my program.

Uprobes can be attached 3 different ways:

1. To a shared library - identified by name
2. To all instances of process - identified by path "/bin/bash"
3. To a specific instance of process - identified by path and pid e,g "/bin/bash" pid 9

### bpfd

1. Adjust the gRPC API to allow the attachment of uprobes, for the required fields in `AttachInfo` see: https://docs.aya-rs.dev/user/aya/programs/uprobe/struct.uprobe
1. Add logic to load uprobes

### bpfd-operator

1. Adjust the CRD to allow for the attachment of uprobe programs
2. This will include a `podSelector` to target specific pods within the cluster, similar to what is used in `NetworkPolicy`.

### Challenges

Containers make uprobe attachment a tricky business.
We will need to enforce [Process Namespace Sharing](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) on pods that want uprobes.
Then we will spawn a sidecar container to load programs with access to bpffs so the program can be pinned.
Unload is simply a case of removing the pin and doesn't require a sidecar.
The use of a sidecar container is needed to run in the same process namespace as the containers in a pod.

What we'll need to be sure of is whether attachment through `/proc/$pid/root` will work, where `$pid` is the entrypoint process of a container in the pod.

### Aya considerations

The existing uprobe API should work fine for our usecases, although we may want to add an alternative API that doesn't do symbol resolution, but instead allows the caller to provide the symbol offset directly.

**Comment by astoycos** [comment]
@anfredette Is his complete?

**Comment by anfredette** [comment]
I still need to do the k8s support, which I've started.
