### ISSUE TITLE
BpfdCore: Automated testing improvements

### ISSUE THREAD

**Issue by anfredette** [bpfd-dev/bpfd#394]
Much of our automated testing involves loading and unloading programs, but we don't have much automated testing that verifies that the BPF programs are actually working as expected.  We need to do more analysis and design, but here are some ideas:

- May be done in integration and/or E2E testing.
- Ways to confirm programs are running/working right
  - logs
  - bpf_printk
  - confirm whether packets flow based on the priorities of XDP and TC drop and allow programs. 
- Confirm the following functionality
  - proceedon settings.
  - global data is getting set correctly.
  - multi-attach programs are prioritized correctly.
  - tracing programs actually trace

**Comment by Billy99** [comment]
In addition, noticed, the `basic-integration-test` starts bpfd, the runs `bpfctl help` to make it can talk to bpfd. We change `bpfctl help` to be processed without going to bpfd, so that test really isn't doing anything. This need to change it to `bpfctl list`.
