### ISSUE TITLE
Move bpfd to a new GitHub Organization

### ISSUE THREAD

**Issue by anfredette** [bpfd-dev/bpfd#397]
bpfd is currently hosted in the Red Hat Emerging Technologies GitHub organization.  As bpfd matures and is gaining interest from outside of Red Hat, it seems appropriate to move the bpfd repo into its own organization.

There is already an org called "[bpfd](https://github.com/bpfd)" which is private, so we need to find another name.  I propose we move it to an org called "[bpfd-dev](https://github.com/bpfd-dev)" (which I have reserved pending our decision).

Please comment on this issue with your opinions on the move.

**Comment by astoycos** [comment]
@shaneutt we'd like you opinion here :)

**Comment by stflaherty** [comment]
I support the move to Org bpfd-dev

**Comment by shaneutt** [comment]
If the intention is to make an org that's _solely_ focused on BPFD then `bpfd-dev` seems OK to me. If the intention is to make an org that is more generally focused on solving higher level and management problems in the ebpf space, maybe we would consider something like `ebpf-tools` (which is available at the time of writing)? Just double checking what our goals as an org are.

**Comment by anfredette** [comment]
Good question.  I was thinking that this would be for bpfd only, but the broader umbrella is worth thinking about.  Does anyone have opinions on this alternative?

**Comment by astoycos** [comment]
I think for now our main focus _is_ a bit narrower and focused on bpfd specifically.  I worry if we make more of an abstract repo it could lead to some confusion.  In the future if the work stored there becomes broader we could always think about moving it again or renaming the org if needed.

**Comment by shaneutt** [comment]
Ok, +1 for `bpfd-dev` then :+1:

**Comment by anfredette** [comment]
Done.

Moved to https://github.com/bpfd-dev/
