### ISSUE TITLE
Create a new demo: Kubecon NA2023

### ISSUE THREAD

**Issue by dave-tucker** [bpfd-dev/bpfd#415]
We should have a video - pointed to in the repo.
And instructions for how to run this demo yourself.

Demo should show:

- The world without bpfd
  - Unable to do xdp multi-attach
  - Unable to do tc multi-attach
  - Having to create operators and boilerplate for your own bpf-enabled application on k8s
  
- The world with bpfd
  - Can do all of the above
  - Dev experience is better

**Comment by astoycos** [comment]
Done in https://sched.co/1R2wG!! 

Demo can be found in https://github.com/bpfd-dev/bpfd/tree/kubecon-demo-2023
