### ISSUE TITLE
Allow for pre-pulling of bytecode images

### ISSUE THREAD

**Issue by astoycos** [bpfd-dev/bpfd#429]
Now that we have support for Image Pull Policy we should allow users to pre-pull images (before a program load request) 

The way I see it is we can 

1. Keep core privileged functionality limited to bpfd and add a `pull_bytecode` command to the API
2. Allow bpfctl to pull and deposit bytecode images into the bpfd image content store (this would unfortunately be a privileged operation since bpfctl would need to access /var/lib/bpfd) 

I'm leaning towards 1 but would like to hear other's opinions as well. 

cc @dave-tucker

**Comment by dave-tucker** [comment]
1. is fine and would result in a `bpfctl pull` command anyway.
