### ISSUE TITLE
bpf programs can be created with non-uuid4 IDs

### ISSUE THREAD

**Issue by dave-tucker** [bpfd-dev/bpfd#444]
```shell
$ ./target/debug/bpfctl load-from-image --id notauuid --image-url quay.io/bpfd-bytecode/xdp_pass:latest xdp  --iface enp8s0 --priority 50

notauuid
```

This is because 624b991 replaced the `HashMap<UUID, Program>` with a `HashMap<String, Program>` which prevented us doing validation on the String that was given to bpfd over the gRPC API.

**Comment by astoycos** [comment]
Finished in #446
