### ISSUE TITLE
Check for existence of `clsact` qdisc when call to create fails

### ISSUE THREAD

**Issue by anfredette** [bpfd-dev/bpfd#468]
The code currently ignores the error when creating the `clsact` qdisc assuming that if there's an error, it must already exist.  
https://github.com/bpfd-dev/bpfd/blob/main/bpfd/src/multiprog/tc.rs#L122

However, if another user has added the `ingress` qdisc, the call would also fail, but the subsequent attempt to add our dispatcher program to the `clsact` qdisc would fail.  

So, if we get an error on the create call, we need to handle it in some way.  Options include:

1. Use the existing ingress qdisc instead and only support ingress attachments on the given interface
2. Return an error
3. Delete the ingress qdisc and add clsact

I'm currently leaning toward 1. because it allows for better cooperation with other apps that are already running.

**Comment by navarrothiago** [comment]
I've been looking into the issue. If another user has added the ingress qdisc, I guess we can assume that this user will manage the qdisc. I'm wondering if, following option 1, our program might be in an unknown state after the qdisc is deleted. This could mean that our BPF programs attached to the ingress qdisc would be removed unexpectedly. Then, I believe we can't rely on that. Does it make sense?

**Comment by anfredette** [comment]
@navarrothiago thanks for looking at this.  It is true that if the other user/program deletes the qdisc, any programs we've attached will get deleted.  That's also true if we are using clsact and another user deletes it without us knowing.  In any case, it's probably safer for us to go with option 2 and return an error if the ingress qdisc already exists because that means that another user is already active on the system.  We may also want to check for the clsact qdisc before blindly adding it.  I'm not sure whether this is possible, but another thought is that it would be good if we could get notified if a clsact qdisc is deleted.  That would at least allow us to clean up our state and report an error.

Also, this illustrates some of the challenges we can have when multiple applications are managing their eBPF programs independently.  I.e., it's easy for them to step on each other.

**Comment by navarrothiago** [comment]
@anfredette, could you assign the issue to me?
