### ISSUE TITLE
kernel ids - the one true program identifier

### ISSUE THREAD

**Issue by dave-tucker** [bpfd-dev/bpfd#580]
bpfd currently allocates a UUID for every loaded program.
this serves a few purposes:

1. It gives us a sentinel value that we can use for storing things on the filesystem
2. It helps us stay in sync when bpfd is driven by an orchestrator
3. Our UUIDs *should* be unique across the cluster

However, the kernel has it's own program/link/map identifiers.
- These are a u32, you provided by the kernel at load/create time.
- They are locally significant

We should preferably have only one unique means of identifying programs when using bpfd/bpfctl.
This should be the kernel ID for consistency with other tools, like bpftool.

Therefore, any UUID from an orchestrator should get stored in the program metadata instead.
Map pin paths will no longer be easily used from K8s - this now needs to be fixed in the design of #522

**Comment by astoycos** [comment]
Mirroring some notes from slack

```
yeah so in my opinionated worldview
get is only useful if you know the resource id - in this case kernel ID of the program.
If you are a CO, you do a List where the predicate is orchestrator_uuid_key == $value and you expect one result back, or error out.
```
