### ISSUE TITLE
undefined reference to `memfd_create

### ISSUE THREAD

**Issue by codearun** [bpfd-dev/bpfd#582]
Attempting to compile bpfd using cargo and rust using a centos7 container with glibc 2.17.

Reaching out to rust team: this is the diagnosis -  "memfd_create was only added in glibc 2.27. Your glibc version must be older than that. If bpfd relies on that function there's nothing you can do other than trying to patch it to not use it."

I did not find any code references for memfd in bpfd code, so why it would pull this function and fail on linking bpfd binary 

 = note: /root/bpfd/target/debug/deps/libnix-88419a1a5e2dc939.rlib(nix-88419a1a5e2dc939.nix.7362adce594dd248-cgu.15.rcgu.o): In function `nix::sys::memfd::memfd_create::h40fdd5a3e8b57bfd':
          /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.2/src/sys/memfd.rs:56: undefined reference to `memfd_create'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `bpfd` (bin "bpfd") due to previous error

Thank you

**Comment by astoycos** [comment]
Hiya @codearun one of the rust crates that bpfd uses (it looks like the nix crate) most likely is not compatible with older kernels, Also it looks like the crate will compile the memfd module regardless of any feature flags (although at runtime you can turn it off by removing the `fd` feature).  However I am not the crate expert so I'll revert to @dave-tucker on that 


Regardless of this one build error though, I think it will be difficult to run bpfd on kernels older than 4.18 due to the fact that the kernel's BPF subsystem has undergone many changes very recently. Is there any way you could try on ma

Is there any way you could bump the OS version you're running with? GLIBc quite old being released all the way back in 2012 😄

**Comment by Billy99** [comment]
@codearun I have a CentOS 7 sever I develop on, but all my eBPF work is done in a Fedora 37 VM running on the server, just to get a newer kernel and newer BPF features. I'll try to build on my server over the weekend, but you may find better luck in a VM. Just a thought.

**Comment by codearun** [comment]
> 

Thank you @Billy99

**Comment by codearun** [comment]
Although my requirement is to get this on a el7 environment , let me try to build this in el9 OS level, to see if the issue goes away.  Thank you @astoycos  , will post here the results.

**Comment by anfredette** [comment]
@codearun, I noticed that you also opened an issue on https://github.com/genuinetools/bpfd that mentioned this project.  As an FYI, although the two projects have the same name, they are not related.

**Comment by codearun** [comment]
build on rhel9 is sucessful, I am hitting a run time issue 


[root@5d9bc19e5dac debug]# ./bpfd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EPERM', bpfd/src/main.rs:63:79
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1076:23
   4: bpfd::main::{{closure}}
             at /root/bpfd/bpfd/src/main.rs:63:13
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:31
   9: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/blocking.rs:66:9
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  11: tokio::runtime::context::runtime::enter_runtime
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:313:45
  14: bpfd::main
             at /root/bpfd/bpfd/src/main.rs:38:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

potentially due to the fact, I am running in  a container. ?

**Comment by astoycos** [comment]
@codearun You'll need to run with `sudo` here unless running via systemd see https://bpfd.netlify.app/getting-started/tutorial/#systemd-service

**Comment by astoycos** [comment]
Closing this for now, please re-open if needed! :)
