### ISSUE TITLE
Use comfy table for `bpfctl get`

### ISSUE THREAD

**Issue by astoycos** [bpfd-dev/bpfd#601]
Follow up to #570 refactor the `bpfctl get` to use a comfy table output rather than straight printing which is a pain :)

**Comment by navarrothiago** [comment]
I was checking some "good first issue" to start with, but it seems this one was already done in https://github.com/bpfd-dev/bpfd/pull/690, right?

**Comment by astoycos** [comment]
Ahhh yep this was That's my bad for not closing, thanks for noticing @navarrothiago! 

Feel free to choose another one or reach out in slack if you don't see something that interests you!
