### ISSUE TITLE
Report bpfd load errors better in k8s

### ISSUE THREAD

**Issue by anfredette** [bpfd-dev/bpfd#659]
Currently, when bpfdagentinternal.LoadBpfdProgram() fails, we log an error and record the condition bpfdiov1alpha1.BpfProgCondNotLoaded in the BpfProgram object.  As a result, the user needs to get the log file and find the error to figure out why the program didn't get loaded.

We should do a better job of reporting the failure reasons for the load failures so the user doesn't need to search the logs.  We should be able to do this via additional conditions recorded in the BpfProgram object.

**Comment by astoycos** [comment]
Closing this in favor of #430
