### ISSUE TITLE
Don't panic on remove_dir_all() in test_pull_bytecode if the dir doesn't exist

### ISSUE THREAD

**Issue by anfredette** [bpfd-dev/bpfd#680]
`sudo ./scripts/setup.sh uninstall` deletes all bpfd info, so if you try to run integration test after running the uninstall script, `test_pull_bytecode()` panics when trying to remove `/var/lib/bpfd/io.bpfd.image.content` if it doesn't exist.

**Comment by astoycos** [comment]
Fixed in #694

**Comment by anfredette** [comment]
Closing per the above comment.
